version: "3"
services:
  server:
    image: cleantogos
    container_name: "cleantogos"
    build: ./
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: on-failure
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    env_file: .docker.env
    ports:
      - "5432:5432"
    restart: unless-stopped
  adminer:
    image: adminer
    links:
      - postgres:postgres
    depends_on:
      - postgres
    ports:
      - "8060:8080"
